model:
  name: "METER"
  variant: "xxs"  # xxs, xs, s

training:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 30
  log_step_loss: True
  selectivity: true
  lambda: 1 # selecitivty factor, about 1% of max depth
  n_of_bins: 64 # bins for selectivity

data:
  root: "data/nyu_data/data"
  split_files_folder: "./data_splits"
  train_val_split: [0.9, 0.1]
  num_workers: 8
  shuffle: true

device:
  cuda: true
  device_id: 0

logging:
  log_interval: 0 # steps -- 0 for no log
  save_interval: 5 # epochs
  experiment_name: 'exp9'
  checkpoint_dir: "./checkpoints"
  log_dir: "./logs"